version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7188
    image: msc-workflow-ms-web-1:latest
    volumes:
      - .:/app
    ports:
      - "7188:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7188/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
